package homework2;

public class TestClass4 {
	public static void main(String[] args) {
		long startTime = System.nanoTime();
		int[] isOk= {0};
		int numOfUser=0;
		Account onuratasever = new Account("onuratasever", "24.02.2002", "Bursa", ++numOfUser);
		Account keremgobekcioglu = new Account("keremgobekcioglu", "18.01.2001", "Sakarya", ++numOfUser);
		Account salihkaragollu = new Account("salihkaragollu", "15.07.2001", "Tokad", ++numOfUser);
		Account busedenizhanayli = new Account("busedenizhanayli", "22.07.2002", "Aydın", ++numOfUser);
		Account recepfurkanakin = new Account("recepfurkanakin", "unknown", "İstanbul", ++numOfUser);
		Account bacar = new Account("beyzaacar", "18.06.2002", "İzmir", ++numOfUser);
		Account buketgencer = new Account("buketgencer", "12.05.2000", "Angara", ++numOfUser);
		Account bilalgokce = new Account("bilalgokce", "10.05.2001", "newCity", ++numOfUser);
		Account mahirkayadelen = new Account("mahirkayadelen", "unknown", "Adana", ++numOfUser);
		Account omercanatli = new Account("omercanatli", "unknown", "Balıkesir", ++numOfUser);
		Account zehraroselover = new Account("zehragulsever", "unknown", "Kandıra", ++numOfUser);
		
		onuratasever.LogIn(isOk);
		onuratasever.sharePost("I don't know how to pass this course :(");
		onuratasever.follow(busedenizhanayli);
		onuratasever.follow(keremgobekcioglu);
		onuratasever.follow(bilalgokce);
		onuratasever.LogOut(isOk);
		bilalgokce.LogIn(isOk);
		bilalgokce.follow(omercanatli);
		bilalgokce.likePost(onuratasever, 1);
		bilalgokce.viewProfile(onuratasever);
		bilalgokce.viewPosts(onuratasever);
		bilalgokce.likePost(onuratasever, 1);
		bilalgokce.addComment(onuratasever, 1, "It is too easy. I can teach you!");
		bilalgokce.sharePost("I don't know how to pass C++ course :(");
		bilalgokce.LogOut(isOk);
		busedenizhanayli.LogIn(isOk);
		busedenizhanayli.viewProfile(onuratasever);
		busedenizhanayli.viewPosts(onuratasever);
		busedenizhanayli.showInteractions(onuratasever);
		busedenizhanayli.addComment(onuratasever, 1, "I don't even know how to pass C course but la France est parfaite :D");
		busedenizhanayli.sharePost("And this is Eifel Tower...");
		busedenizhanayli.sharePost("My dear friend Hafsa came here to Paris to celebrate her birthday!");
		busedenizhanayli.LogOut(isOk);
		onuratasever.LogIn(isOk);
		onuratasever.sendMessage(bilalgokce, "Good luck passing C++ course ahahaha!");
		onuratasever.viewProfile(busedenizhanayli);
		onuratasever.viewPosts(busedenizhanayli);
		onuratasever.likePost(busedenizhanayli, 1);
		onuratasever.addComment(busedenizhanayli, 2, "İnsanlar bu hayatı yaşıyor abi ya!");
		onuratasever.showInteractions(busedenizhanayli);
		onuratasever.checkInbox();
		onuratasever.checkOutbox();
		onuratasever.viewOutbox();
		onuratasever.LogOut(isOk);
		bilalgokce.LogIn(isOk);
		bilalgokce.checkInbox();
		bilalgokce.viewInbox();
		bilalgokce.block(onuratasever);
		bilalgokce.LogOut(isOk);
		salihkaragollu.LogIn(isOk);
		salihkaragollu.follow(recepfurkanakin);
		salihkaragollu.follow(onuratasever);
		salihkaragollu.viewProfile(busedenizhanayli);
		salihkaragollu.viewPosts(busedenizhanayli);
		salihkaragollu.likePost(busedenizhanayli, 1);
		salihkaragollu.addComment(busedenizhanayli, 1, "Poland is better!!!");
		salihkaragollu.showInteractions(busedenizhanayli);
		//unlike and uncomment
		salihkaragollu.unlike(busedenizhanayli, 1);
		salihkaragollu.uncomment(busedenizhanayli, 1);
		salihkaragollu.showInteractions(busedenizhanayli);
		salihkaragollu.viewProfile(onuratasever);
		salihkaragollu.viewPosts(onuratasever);
		salihkaragollu.likePost(onuratasever, 1);
		salihkaragollu.addComment(onuratasever, 1, "Never mind come to party!");
		salihkaragollu.LogOut(isOk);
		onuratasever.LogIn(isOk);
		onuratasever.viewProfile(bilalgokce);
		onuratasever.LogOut(isOk);
		bilalgokce.LogIn(isOk);
		// bilal is removed
		bilalgokce.unblock(onuratasever);
		bilalgokce.unfollow(omercanatli);
		bilalgokce.follow(zehraroselover);
		bilalgokce.showHistory();
		bilalgokce.LogOut(isOk);
		onuratasever.LogIn(isOk);
		onuratasever.follow(omercanatli);
		onuratasever.follow(bacar);
		onuratasever.follow(buketgencer);
		onuratasever.showHistory();
		onuratasever.unfollow(keremgobekcioglu);
		onuratasever.viewProfile(onuratasever);
		onuratasever.follow(mahirkayadelen);
		onuratasever.sendMessage(mahirkayadelen, "When abi when?");
		onuratasever.LogOut(isOk);
		mahirkayadelen.LogIn(isOk);
		mahirkayadelen.checkInbox();
		mahirkayadelen.viewInbox();
		mahirkayadelen.block(onuratasever);
		mahirkayadelen.LogOut(isOk);
		bacar.LogIn(isOk);
		bacar.viewProfile(onuratasever);
		bacar.showHistory();
		bacar.LogOut(isOk);
		salihkaragollu.LogIn(isOk);
		salihkaragollu.unlike(onuratasever, 1);
		salihkaragollu.viewProfile(onuratasever);
		salihkaragollu.viewPosts(onuratasever);
		salihkaragollu.showInteractions(onuratasever);
		salihkaragollu.showHistory();
		salihkaragollu.LogOut(isOk);
		long elapsedTime = System.nanoTime() - startTime;
		System.out.println("Total execution time to create 1000K objects in Java in millis: "
                + elapsedTime/1000000);
	} 
}
